[package]
name = "sshidentify"
version = "0.1.0"
authors = ["Sebastian Reichel <sre@ring0.de>"]

[dependencies]
nix = "0.10.0"
libc = "0.2"
systemd = "~0.2"
regex = "0.2"
base64 = "~0.6.0"
sha2 = "0.7.1"
md5 = "0.3.7"
