[package]
name = "sshidentify"
version = "0.1.1"
authors = ["Sebastian Reichel <sre@ring0.de>"]

[dependencies]
nix = "0.15.0"
libc = "0.2.65"
systemd = "0.4.0"
regex = "1.3.1"
base64 = "0.11.0"
sha2 = "0.8.0"
md5 = "0.7.0"
