[package]
name = "sshidentify"
version = "0.1.2"
authors = ["Sebastian Reichel <sre@ring0.de>"]

[dependencies]
nix = "0.20"
libc = "0.2"
systemd = "0.9"
regex = "1.5"
base64 = "0.13"
sha2 = "0.9"
md5 = "0.7"
home = "0.5"
